consul:
    image: progrium/consul
    ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"
    command:
        -server 
        -bootstrap 
        -ui-dir /ui
        -advertise 10.50.1.16
registrator:
    image: gliderlabs/registrator
    command: consul://10.50.1.16:8500
    hostname: $HOSTNAME
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
nginx:
    build: ./nginx
    dns: 172.17.42.1
    ports:
        - "80:80"
getnode1:
    build: ./get_node
    dns: 172.17.42.1
    ports:
        - "8080"
getnode2:
    build: ./get_node
    dns: 172.17.42.1
    ports:
        - "8080"
postnode1:
    build: ./post_node
    dns: 172.17.42.1
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"