#!/bin/bash
# Get IP address of host
ipAddr=$(ip route get 8.8.8.8 | awk 'NR==1 {print $NF}')

docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)

# Consul
docker run -p 8400:8400 -p 8500:8500 -p $ipAddr:53:53/udp -h node1 -d --name consul progrium/consul -server -bootstrap -ui-dir /ui -advertise $ipAddr

# Registrator
docker run -h $HOSTNAME -v /var/run/docker.sock:/tmp/docker.sock -d --name registrator gliderlabs/registrator consul://$ipAddr:8500

# Redis
docker run -d -p 6379:6379 --name redis redis

# Get Nodes
docker build -t getnode ./get_node
docker run -d --name getnode1 -p 8081:8080 --dns=$ipAddr --dns-search=service.consul -e "SERVICE_TAGS=api" getnode 
docker run -d --name getnode2 -p 8082:8080 --dns=$ipAddr --dns-search=service.consul -e "SERVICE_TAGS=api" getnode 

# Post node 
docker build -t postnode ./post_node
docker run -d --name postnode1 -p 8083:8080 --dns=$ipAddr --dns-search=service.consul -e "SERVICE_TAGS=api" postnode 

# Nginx
docker build -t nginx ./nginx
docker run -d -p 80:80 --name nginx --dns=$ipAddr --dns-search=service.consul nginx