nginx:
    build: ./nginx
    links:
        - nodeGet1:node1
        - nodeGet2:node2
        - nodePost1:node3
    ports:
        - "80:80"
nodeGet1:
    build: ./get_node
    links:
        - redis
    ports:
        - "8080"
nodeGet2:
    build: ./get_node
    links:
        - redis
    ports:
        - "8080"
nodePost1:
    build: ./post_node
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"