nginx:
    build: ./nginx
    links:
        - node_get1:node1
        - node_get1:node2
        - node_post1:node3
    ports:
        - "80:80"
node_get1:
    build: ./get_node
    links:
        - redis
    ports:
        - "8080"
node_get1:
    build: ./get_node
    links:
        - redis
    ports:
        - "8080"
node_post1:
    build: ./post_node
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"