consul:
    image: progrium/consul
    ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"
    command:
        -server 
        -bootstrap 
        -ui-dir /ui 
        -advertise 192.168.99.101
registrator:
    image: gliderlabs/registrator
    command: consul://192.168.99.101:8500
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
nginx:
    build: ./nginx
    links:
        - getnode1
        - getnode2
        - postnode1
    ports:
        - "80:80"
getnode1:
    build: ./get_node
    links:
        - redis
    ports:
        - "8080"
getnode2:
    build: ./get_node
    links:
        - redis
    ports:
        - "8080"
postnode1:
    build: ./post_node
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"