nginx:
    build: ./nginx
    links:
        - getnode1
        - getnode2
        - postnode1
    ports:
        - "80:80"
getnode1:
    build: ./get_node
    links:
        - redis
    ports:
        - "8080"
getnode2:
    build: ./get_node
    links:
        - redis
    ports:
        - "8080"
postnode1:
    build: ./post_node
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"